services:
  proxy:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    user: root
    restart: always

  web:
    image: nginx:latest
    container_name: web
    labels:
      - "dockname.domain=web.localhost"
      - "dockname.port=80"